app-id: org.fptn.VPN
runtime: org.freedesktop.Platform
runtime-version: "23.08"
sdk: org.freedesktop.Sdk
command: fptn-client
modules:
  - name: fptn
    buildsystem: simple
    build-commands:
      - cp build/src/fptn-client/fptn-client /app/bin/
      - install -Dm644 deploy/linux/fptn.desktop /app/share/applications/org.fptn.VPN.desktop
    sources:
      - type: git
        url: https://github.com/fptn-project/fptn.git
        branch: master
